#!/usr/bin/env python
"""
Unit test build entry point.
"""

from SCons.Script import Default, Dir, Import, Return

Import("root_env", "build_unit_tests", "project_root")

test_program = build_unit_tests(root_env, project_root, tests_root=Dir(".").srcnode().abspath)

top_dir = Dir("#").abspath
tests_dir = Dir(".").srcnode().abspath
if top_dir == tests_dir:
    Default(test_program)

Return("test_program")
