name: Build

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  actions: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Setup Build Tools
        uses: ./.github/actions/setup-build-tools

      - name: Build debug artifacts
        run: ./scripts/build_debug.sh

      - name: Build unit test binary
        run: python ./scripts/run_unit_tests.py --gtest_list_tests >/dev/null

      - name: Build integration test artifacts
        run: scons integration_tests

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: stagehand-build-artifacts
          path: |
            bin/**
            build/obj/**
            tests/unit/build/**
          if-no-files-found: error
          retention-days: 1
